"""url analyses

Revision ID: 87ccfa016448
Revises: c0bc4f36a11d
Create Date: 2026-10-06 22:19:46.757464
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '87ccfa016448'
down_revision: Union[str, None] = 'c0bc4f36a11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('chunks_analyzed', sa.Integer(), nullable=False),
    sa.Column('sentiment_distribution', sa.Text(), nullable=False),
    sa.Column('mean_class_scores', sa.Text(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_analyses_created_at'), 'url_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_url_analyses_overall_sentiment'), 'url_analyses', ['overall_sentiment'], unique=False)
    op.create_index('ix_url_analyses_user_created', 'url_analyses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_url_analyses_user_id'), 'url_analyses', ['user_id'], unique=False)
    op.drop_index(op.f('ix_results_prediction_created'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_created_at'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_live_item_id'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_prediction'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_live_data_content_hash'), table_name='live_data')
    op.drop_index(op.f('ix_live_data_created_at'), table_name='live_data')
    op.drop_index(op.f('ix_live_data_published_at'), table_name='live_data')
    op.drop_index(op.f('ix_live_data_source'), table_name='live_data')
    op.drop_table('live_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('live_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prediction', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('class_scores', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['live_item_id'], ['live_data.id'], name=op.f('sentiment_results_live_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sentiment_results_pkey'))
    )
    op.create_index(op.f('ix_sentiment_results_prediction'), 'sentiment_results', ['prediction'], unique=False)
    op.create_index(op.f('ix_sentiment_results_live_item_id'), 'sentiment_results', ['live_item_id'], unique=True)
    op.create_index(op.f('ix_sentiment_results_created_at'), 'sentiment_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_results_prediction_created'), 'sentiment_results', ['prediction', 'created_at'], unique=False)
    op.create_table('live_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('live_data_pkey'))
    )
    op.create_index(op.f('ix_live_data_source'), 'live_data', ['source'], unique=False)
    op.create_index(op.f('ix_live_data_published_at'), 'live_data', ['published_at'], unique=False)
    op.create_index(op.f('ix_live_data_created_at'), 'live_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_live_data_content_hash'), 'live_data', ['content_hash'], unique=True)
    op.drop_index(op.f('ix_url_analyses_user_id'), table_name='url_analyses')
    op.drop_index('ix_url_analyses_user_created', table_name='url_analyses')
    op.drop_index(op.f('ix_url_analyses_overall_sentiment'), table_name='url_analyses')
    op.drop_index(op.f('ix_url_analyses_created_at'), table_name='url_analyses')
    op.drop_table('url_analyses')
    # ### end Alembic commands ###
