"""initial schema

Revision ID: c0bc4f36a11d
Revises: 
Create Date: 2026-10-05 21:13:44.070424
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0bc4f36a11d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_data_content_hash'), 'live_data', ['content_hash'], unique=True)
    op.create_index(op.f('ix_live_data_created_at'), 'live_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_live_data_published_at'), 'live_data', ['published_at'], unique=False)
    op.create_index(op.f('ix_live_data_source'), 'live_data', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('prediction', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('simple_explanation', sa.Text(), nullable=False),
    sa.Column('technical_explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_prediction'), 'predictions', ['prediction'], unique=False)
    op.create_index('ix_predictions_user_created', 'predictions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_item_id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('class_scores', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['live_item_id'], ['live_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_results_prediction_created', 'sentiment_results', ['prediction', 'created_at'], unique=False)
    op.create_index(op.f('ix_sentiment_results_created_at'), 'sentiment_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_sentiment_results_live_item_id'), 'sentiment_results', ['live_item_id'], unique=True)
    op.create_index(op.f('ix_sentiment_results_prediction'), 'sentiment_results', ['prediction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_results_prediction'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_live_item_id'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_created_at'), table_name='sentiment_results')
    op.drop_index('ix_results_prediction_created', table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index('ix_predictions_user_created', table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_live_data_source'), table_name='live_data')
    op.drop_index(op.f('ix_live_data_published_at'), table_name='live_data')
    op.drop_index(op.f('ix_live_data_created_at'), table_name='live_data')
    op.drop_index(op.f('ix_live_data_content_hash'), table_name='live_data')
    op.drop_table('live_data')
    # ### end Alembic commands ###
